In [42]:
# bring libraries into scope
import numpy as np
import math
import sys
import pandas as pd

# set print options
np.set_printoptions(threshold=np.nan)

# import data
p2file = "/Users/C3P0/Code/OMSCS/CS7646_ML4T/Projects/MC3_P1/mc3p1_assess_learners/Istanbul.csv"
inf = open(p2file)
data = np.array([map(float,s.strip().split(',')[1:]) for s in inf.readlines()[1:]])

# compute how much of the data is training and testing
train_rows = int(0.6* data.shape[0])
test_rows = data.shape[0] - train_rows

# separate out training and testing data
trainX = data[:train_rows,0:-1]
trainY = data[:train_rows,-1]
testX = data[train_rows:,0:-1]
testY = data[train_rows:,-1]

# rename train data as dataX and DataY to develop final function
dataX = trainX
dataY = trainY

# set seed
np.random.seed(2)

In [70]:
def buildTree(dataX, dataY, leafsize):
    if dataX.shape[0] <= leafsize:
        return np.array([[-1, dataY.mean(), np.nan, np.nan]])
    elif dataY.std() == 0:
        return np.array([[-1, dataY.mean(), np.nan, np.nan]])
    else:
        i, splitVal, leftX, rightX, leftY, rightY, leftleaf = findNonEmptyRandomSplit(dataX, dataY)
        
        if leftleaf.size == 0:
            lefttree = buildTree(leftX, leftY, leafsize)
            righttree = buildTree(rightX, rightY, leafsize)
            root = np.array([[i, splitVal, 1, lefttree.shape[0] + 1]])
            fin_array = np.append(root, lefttree, axis=0)
            fin_array = np.append(fin_array, righttree, axis=0)
            return fin_array
        else:
            lefttree = np.append(lefttree, leftleaf, axis=0)
            righttree = buildTree(rightX, rightY, leafsize)
            root = np.array([[i, splitVal, 1, lefttree.shape[0] + 1]])
            fin_array = np.append(root, lefttree, axis=0)
            fin_array = np.append(fin_array, righttree, axis=0)
            return fin_array            

In [73]:
def findNonEmptyRandomSplit(dataX, dataY):
    counter = 0   # start counter
    
    while counter <= 10:
        counter = counter + 1   # increment counter
        
        i = np.random.randint(0, dataX.shape[1])    # randomly select a feature
        j = np.random.randint(0, dataX.shape[0])    # randomly select element 1 in i
        k = np.random.randint(0, dataX.shape[0])    # randomly select element 2 in i
        
        splitVal = (dataX[j, i] + dataX[k, i]) / 2  # find the value to split on
        
        # build left and right X and Y based off of splitVal
        leftIndex = np.where(dataX[:,i] <= splitVal)
        rightIndex = np.where(dataX[:,i] > splitVal)
        leftX = dataX[leftIndex]
        leftY = dataY[leftIndex]
        rightX = dataX[rightIndex]
        rightY = dataY[rightIndex]
        
        if leftX.size == 0:
            if counter == 10:
                leaf = np.array([[-1, leftY.mean(), np.nan, np.nana]])
                return i, splitVal, leftX, rightX, leftY, rightY, leaf
            else:
                pass
        else:
            leaf = np.array([])
            return i, splitVal, leftX, rightX, leftY, rightY, leaf

In [128]:
model = buildTree(dataX, dataY, 100)

In [139]:
model_df = pd.DataFrame(model).head(20) 
model_df

0         1   2   3
0  0  0.004669   1   6
1  7 -0.006351   1   2
2 -1 -0.009822 NaN NaN
3  6  0.004569   1   2
4 -1  0.000023 NaN NaN
5 -1  0.000846 NaN NaN
6  7  0.011014   1   2
7 -1  0.003170 NaN NaN
8 -1  0.016037 NaN NaN

In [191]:
pt_df = pd.DataFrame(dataX[[0]])
pt_df

0         1         2         3         4  5        6         7
0  0.035754  0.038376 -0.004679  0.002193  0.003894  0  0.03119  0.012698

In [204]:
def query(pts, model):
    predY = np.apply_along_axis(queryPT, 1, pt, model)
    return predY

In [202]:
def queryPT(pt, model):
    index = 0
    node = model[index]
    feature, splitVal, indexL, indexR = node
    feature = int(feature)
    indexL = int(indexL)
    indexR = int(indexR)
    while feature != -1:
        if pt[feature] <= splitVal:
            index = index + indexL
            node = model[index]
            feature, splitVal, indexL, indexR = node
            feature = int(feature)
            try:
                indexL = int(indexL)
                indexR = int(indexR)
            except ValueError:
                pass
            if feature == -1:
                return splitVal
            else:
                pass
        else:
            index = index + indexR
            node = model[index]
            feature, splitVal, indexL, indexR = node
            feature = int(feature)
            try:
                indexL = int(indexL)
                indexR = int(indexR)
            except ValueError:
                pass
            if feature == -1:
                return splitVal
            else:
                pass

In [209]:
predY = query(dataX, model)

In [210]:
rmse = math.sqrt(((trainY - predY) ** 2).sum()/trainY.shape[0])

In [218]:
((trainY-predY)**2).sum()/trainY.shape[0]

7.6350820528838491e-05

In [ ]:
### Newer development code

In [ ]:
### Query

In [ ]:
pt = dataX
test = np.apply_along_axis(queryPT, 1, pt, model)
test_df = pd.DataFrame(test)
test_df

In [ ]:
output = queryPT(dataX[3], model)
output

In [ ]:
output = query(dataX, model)
print output.shape
print dataX.shape

In [ ]:
### Build Tree

In [ ]:
### development
i = 2
j = 35
k = 201
splitval = (dataX[j, i] + dataX[k, i]) / 2
leftX_1 = dataX[dataX[:,i] <= splitval]
leftX.shape

In [ ]:
### development
rightX_1 = dataX[dataX[:,i] > splitval]
rightX.shape

In [60]:
### development
x = np.array([1,2,3,4])
y = np.where(x > i)
x[y]

NameError: name 'i' is not defined

In [ ]:
### development
leftIndex = np.where(dataX[:,i] <= splitval)
rightIndex = np.where(dataX[:,i] > splitval)

leftX = dataX[leftIndex]
leftY = dataY[leftIndex]

rightX = dataX[rightIndex]
rightY = dataY[rightIndex]

In [ ]:
### development
z = 0
c1 = 0
c2 = 0
c3 = 0
x = 2

def testf(z, c1, c2, c3, x):
    while z <= 2:
        z = z + 1
        print "c1 =", c1
        c1 = c1 + 1
        if x == 1:
            print "c2 =", c2
            c2 = c2 + 1
            pass
        else:
            print "c3 =", c3
            c3 = c3 + 1
            return c1, c3, z
            
c1, c3, z = testf(z, c1, c2, c3, x)

print c1, c3, z

In [ ]:
### development
a = np.array([[1,1,1],[2,2,2]])
b = np.array([[3,3,3]])
c = np.array([[]])

np.append(a, b, axis = 0)

In [ ]:
### development
z = np.array([[]])
z.size

if z.size == 0:
    print z.size

In [ ]:
### Old RTLearner Code

In [207]:
def RTLearner(data):
    if data.shape[0] == 1:
        print "1"
        return [[1, data[0,-1], np.nan, np.nan]]
    elif data[:,-1].std() == 0:
        print "2"
        return [[1, data[0,-1], np.nan, np.nan]]
    else:
        print "3"
        np.random.seed(2)
        i = np.random.randint(0, data.shape[1])    # randomly select a feature
        j = np.random.randint(0, data.shape[0])    # randomly select element 1 in i
        k = np.random.randint(0, data.shape[0])    # randomly select element 2 in i
        splitval = (data[j, i] + data[k, i]) / 2
        lefttree = rtlearner(data[data[:,i] <= splitval])
        righttree = rtlearner(data[data[:,i] > splitval])
        root = [i, splitval, 1, lefttree.shape[0]+1]
        fin_array = np.append(root, lefttree, axis=0)
        fin_array = np.append(root, righttree, axis=0)
        return fin_array
    

In [208]:
learner = rtlearner(data)
print learner

3
3
3
3
3
3
3
3
3
1
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3


RuntimeError: maximum recursion depth exceeded while calling a Python object

In [ ]:
### Old Development code below here

In [212]:
data1 = data[0:1,:]
print data1
print data1.shape

[[ 0.03575371  0.03837619 -0.00467931  0.00219342  0.00389438  0.
   0.03119023  0.01269804  0.02852446]]
(1, 9)


In [209]:
data2 = np.array([[0,0,1],[0,0,1],[0,0,1]])
data3 = np.array([[2,2,2],[2,2,2],[2,2,2]])
data4 = np.array([[3,3,3],[3,3,3],[3,3,3]])
#data2 = data2[:,-1]
print data2
print data2.shape

data2 = np.append(data2, data3, axis=0)
data2 = np.append(data2, data4, axis=0)

[[0 0 1]
 [0 0 1]
 [0 0 1]]
(3, 3)


In [211]:
data2

array([[0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [210]:
np.random.seed(2)
i = np.random.randint(0, data.shape[1])
j = np.random.randint(0, data.shape[0])
k = np.random.randint(0, data.shape[0])
splitval = (data[j, i] + data[k, i]) / 2
print i, j, k, splitval

8 527 493 -0.0086172415
